# debug
host: 127.0.0.1
port: 4000

# site
baseurl:
name: vivaxy's Blog
title: vivaxy's Blog
url: http://vivaxyblog.github.io
author:
    name: vivaxy
    email: xyxuye2007@126.com

# plugin
markdown: kramdown

# pagination
paginate: 10
paginate_path: /index/page:num/

exclude: [less, node_modules, package.json, README.md, Gemfile]

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false
kramdown:
    math_engine: mathjax
plugins:
   - jekyll-paginate
